# Generated by Django 5.0 on 2026-10-02 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('meal_type', models.CharField(choices=[('sarapan', 'Sarapan'), ('siang', 'Makan Siang'), ('malam', 'Makan Malam'), ('camilan', 'Camilan')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('estimated_cost', models.PositiveIntegerField(default=0, help_text='Perkiraan biaya dalam Rupiah')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Opsional, dalam kkal', null=True)),
                ('is_homemade', models.BooleanField(default=False, help_text='Masak sendiri, bukan makanan cepat saji')),
                ('packaging_avoided', models.PositiveSmallIntegerField(default=0, help_text='Jumlah kemasan sekali pakai yang dihindari')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]